package server

import (
	"context"
	"net/http"

	"connectrpc.com/connect"

	srev1 "github.com/yourname/ai-sre/backend/internal/gen/sre/v1"
	"github.com/yourname/ai-sre/backend/internal/gen/sre/v1/srev1connect"
	"github.com/yourname/ai-sre/backend/internal/kubectl"
	"github.com/yourname/ai-sre/backend/internal/llm"
)

// SREServer implements srev1connect.SREServiceHandler.
// NOTE: srev1 and srev1connect are generated by `buf generate` — run
// `make proto` before building.
type SREServer struct {
	llm     *llm.Client
	kubectl *kubectl.Executor
}

func New(l *llm.Client, k *kubectl.Executor) *SREServer {
	return &SREServer{llm: l, kubectl: k}
}

// Handler returns the ConnectRPC path and http.Handler for mounting.
func (s *SREServer) Handler() (string, http.Handler) {
	return srev1connect.NewSREServiceHandler(s)
}

// Chat translates the user's message to a kubectl command via the LLM,
// executes it, and streams each phase back as typed chunks.
func (s *SREServer) Chat(
	ctx context.Context,
	req *connect.Request[srev1.ChatRequest],
	stream *connect.ServerStream[srev1.ChatResponse],
) error {
	result, err := s.llm.Ask(ctx, req.Msg.SessionId, req.Msg.Message)
	if err != nil {
		return stream.Send(&srev1.ChatResponse{
			Payload: &srev1.ChatResponse_Error{
				Error: &srev1.ErrorChunk{Message: err.Error()},
			},
		})
	}

	if err := stream.Send(&srev1.ChatResponse{
		Payload: &srev1.ChatResponse_Explanation{
			Explanation: &srev1.ExplanationChunk{Text: result.Explanation},
		},
	}); err != nil {
		return err
	}

	if result.RequiresExecution && result.Command != "" {
		if err := stream.Send(&srev1.ChatResponse{
			Payload: &srev1.ChatResponse_Command{
				Command: &srev1.CommandChunk{Command: result.Command},
			},
		}); err != nil {
			return err
		}

		output, success := s.kubectl.Run(ctx, result.Command)
		if err := stream.Send(&srev1.ChatResponse{
			Payload: &srev1.ChatResponse_Output{
				Output: &srev1.OutputChunk{Text: output, Success: success},
			},
		}); err != nil {
			return err
		}
	}

	return stream.Send(&srev1.ChatResponse{
		Payload: &srev1.ChatResponse_Done{
			Done: &srev1.DoneChunk{},
		},
	})
}
