import { createClient } from '@connectrpc/connect'
import { createConnectTransport } from '@connectrpc/connect-web'
import { SREService } from '../gen/sre/v1/sre_pb'

// NOTE: sre_connect.ts is generated by `buf generate` (make proto).
// Run that before starting the dev server.

const transport = createConnectTransport({
  // Same origin in production (Go serves both the page and the API).
  // In dev, Vite proxies /sre.v1.* to localhost:8080 so this still works.
  baseUrl: window.location.origin,
})

export const client = createClient(SREService, transport)
